USE MuzeuDB
GO

CREATE OR ALTER PROCEDURE dbo.DirtyReads2
@solve BIT
AS
BEGIN
	IF (@solve = 0)
		-- PROBLEM:
		SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	ELSE
		-- SOLUTION:
		SET TRANSACTION ISOLATION LEVEL READ COMMITTED

	BEGIN TRAN -- BEGIN TRANSATION
	SELECT * FROM [MuzeuDB].[dbo].[Vase]
	WAITFOR DELAY '00:00:10'
	SELECT * FROM [MuzeuDB].[dbo].[Vase]
	COMMIT TRAN -- COMMIT TRANSATION
END

GO

-- CALL FOR PROBLEM
EXEC dbo.DirtyReads2 0

-- CALL FOR SOLUTION
EXEC dbo.DirtyReads2 1

SELECT * FROM [MuzeuDB].[dbo].[Vase]