USE MuzeuDB
GO

CREATE OR ALTER PROCEDURE dbo.DirtyReads2
AS
BEGIN
	-- PROBLEM:
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

	-- SOLUTION:
	--SET TRANSACTION ISOLATION LEVEL READ COMMITTED

	BEGIN TRAN -- BEGIN TRANSATION
	SELECT * FROM [MuzeuDB].[dbo].[Vase]
	WAITFOR DELAY '00:00:10'
	SELECT * FROM [MuzeuDB].[dbo].[Vase]
	COMMIT TRAN -- COMMIT TRANSATION
END

GO

EXEC dbo.DirtyReads2

SELECT * FROM [MuzeuDB].[dbo].[Vase]