USE MuzeuDB
GO

CREATE OR ALTER PROCEDURE dbo.PhantomReads2
AS
BEGIN
	-- PROBLEM:
	SET TRANSACTION ISOLATION LEVEL REPEATABLE READ

	-- SOLUTION:
	--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
	
	BEGIN TRAN -- BEGIN TRANSACTION
	SELECT * FROM [MuzeuDB].[dbo].[Vase]
	WAITFOR DELAY '00:00:10'
	SELECT * FROM [MuzeuDB].[dbo].[Vase]
	COMMIT TRAN -- COMMIT TRANSACTION
END

GO

EXEC dbo.PhantomReads2

SELECT * FROM [MuzeuDB].[dbo].[Vase]
DELETE FROM [MuzeuDB].[dbo].[Vase] WHERE VasID = 400
select * from [MuzeuDB].[dbo].[Vase]